Trigger CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,46 +38,70 @@ jobs:
       - name: Run tests
         run: npm test
 
-  sonar-analysis:
-    runs-on: self-hosted
-
+  sonarqube:
+    name: SonarQube
+    runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      
       - name: Install dependencies
         run: npm install
         
       - name: Run tests with coverage
         run: npm run coverage
-      
-      - name: Install SonarScanner
-        run: |
-          curl.exe -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
-          tar -xf sonar-scanner.zip
-          echo "${PWD}/sonar-scanner-5.0.1.3006-windows/bin" >> $GITHUB_PATH
 
       - name: SonarQube Scan
-        run: |
-          sonar-scanner -D"sonar.login=${{ secrets.SONAR_TOKEN }}" -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}"
-
-      - name: Wait for SonarQube analysis to finish
-        run: |
-          sleep 10
-      
-      - name: Get Quality Gate Status
-        id: quality_gate
+        uses: SonarSource/sonarqube-scan-action@v5
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-        run: |
-          $result=curl.exe -s -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=sonar_test"
-          
-          $status = ($result | ConvertFrom-Json).projectStatus.status
 
-          if ($status -eq "OK") {
-              Write-Host "Quality Gate Passed"
-          } else {
-              Write-Host "Quality Gate Failed"
-              exit 1
-          }
+      - name: Check Quality Gate status
+        uses: SonarSource/sonarqube-quality-gate-action@master
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+  # sonar-analysis:
+  #   runs-on: self-hosted
+
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+
+  #     - name: Install dependencies
+  #       run: npm install
+        
+  #     - name: Run tests with coverage
+  #       run: npm run coverage
+      
+  #     - name: Install SonarScanner
+  #       run: |
+  #         curl.exe -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
+  #         tar -xf sonar-scanner.zip
+  #         echo "${PWD}/sonar-scanner-5.0.1.3006-windows/bin" >> $GITHUB_PATH
+
+  #     - name: SonarQube Scan
+  #       run: |
+  #         sonar-scanner -D"sonar.login=${{ secrets.SONAR_TOKEN }}" -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}"
+
+  #     - name: Wait for SonarQube analysis to finish
+  #       run: |
+  #         sleep 10
+      
+  #     - name: Get Quality Gate Status
+  #       id: quality_gate
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+  #       run: |
+  #         $result=curl.exe -s -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=sonar_test"
+          
+  #         $status = ($result | ConvertFrom-Json).projectStatus.status
+
+  #         if ($status -eq "OK") {
+  #             Write-Host "Quality Gate Passed"
+  #         } else {
+  #             Write-Host "Quality Gate Failed"
+  #             exit 1
+  #         }
